package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbBonificaciones generated by hbm2java
 */
public class TbBonificaciones  implements java.io.Serializable {


     private int bonCod;
     private String bonNombre;
     private String bonNombreCorto;
     private Set tbBonificacionesXPersonals = new HashSet(0);

    public TbBonificaciones() {
    }

	
    public TbBonificaciones(int bonCod, String bonNombre, String bonNombreCorto) {
        this.bonCod = bonCod;
        this.bonNombre = bonNombre;
        this.bonNombreCorto = bonNombreCorto;
    }
    public TbBonificaciones(int bonCod, String bonNombre, String bonNombreCorto, Set tbBonificacionesXPersonals) {
       this.bonCod = bonCod;
       this.bonNombre = bonNombre;
       this.bonNombreCorto = bonNombreCorto;
       this.tbBonificacionesXPersonals = tbBonificacionesXPersonals;
    }
   
    public int getBonCod() {
        return this.bonCod;
    }
    
    public void setBonCod(int bonCod) {
        this.bonCod = bonCod;
    }
    public String getBonNombre() {
        return this.bonNombre;
    }
    
    public void setBonNombre(String bonNombre) {
        this.bonNombre = bonNombre;
    }
    public String getBonNombreCorto() {
        return this.bonNombreCorto;
    }
    
    public void setBonNombreCorto(String bonNombreCorto) {
        this.bonNombreCorto = bonNombreCorto;
    }
    public Set getTbBonificacionesXPersonals() {
        return this.tbBonificacionesXPersonals;
    }
    
    public void setTbBonificacionesXPersonals(Set tbBonificacionesXPersonals) {
        this.tbBonificacionesXPersonals = tbBonificacionesXPersonals;
    }




}


