package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TbDescuentos generated by hbm2java
 */
public class TbDescuentos  implements java.io.Serializable {


     private int desCod;
     private TbPersonal tbPersonal;
     private TbGiraduria tbGiraduria;
     private int desMonto;
     private Date desFecha;

    public TbDescuentos() {
    }

    public TbDescuentos(int desCod, TbPersonal tbPersonal, TbGiraduria tbGiraduria, int desMonto, Date desFecha) {
       this.desCod = desCod;
       this.tbPersonal = tbPersonal;
       this.tbGiraduria = tbGiraduria;
       this.desMonto = desMonto;
       this.desFecha = desFecha;
    }
   
    public int getDesCod() {
        return this.desCod;
    }
    
    public void setDesCod(int desCod) {
        this.desCod = desCod;
    }
    public TbPersonal getTbPersonal() {
        return this.tbPersonal;
    }
    
    public void setTbPersonal(TbPersonal tbPersonal) {
        this.tbPersonal = tbPersonal;
    }
    public TbGiraduria getTbGiraduria() {
        return this.tbGiraduria;
    }
    
    public void setTbGiraduria(TbGiraduria tbGiraduria) {
        this.tbGiraduria = tbGiraduria;
    }
    public int getDesMonto() {
        return this.desMonto;
    }
    
    public void setDesMonto(int desMonto) {
        this.desMonto = desMonto;
    }
    public Date getDesFecha() {
        return this.desFecha;
    }
    
    public void setDesFecha(Date desFecha) {
        this.desFecha = desFecha;
    }




}


