package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0



/**
 * TbEstadoCivil generated by hbm2java
 */
public class TbEstadoCivil  implements java.io.Serializable {


     private int ecCod;
     private String ecDescripcion;

    public TbEstadoCivil() {
    }

    public TbEstadoCivil(int ecCod, String ecDescripcion) {
       this.ecCod = ecCod;
       this.ecDescripcion = ecDescripcion;
    }
   
    public int getEcCod() {
        return this.ecCod;
    }
    
    public void setEcCod(int ecCod) {
        this.ecCod = ecCod;
    }
    public String getEcDescripcion() {
        return this.ecDescripcion;
    }
    
    public void setEcDescripcion(String ecDescripcion) {
        this.ecDescripcion = ecDescripcion;
    }




}


