package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbGiraduria generated by hbm2java
 */
public class TbGiraduria  implements java.io.Serializable {


     private int giCod;
     private String giNombreCorto;
     private String giNombreLargo;
     private String giDireccion;
     private String giTelefono;
     private Set tbDescuentoses = new HashSet(0);

    public TbGiraduria() {
    }

    public TbGiraduria(int giCod, String giNombreCorto, String giNombreLargo, String giDireccion, String giTelefono) {
        this.giCod = giCod;
        this.giNombreCorto = giNombreCorto;
        this.giNombreLargo = giNombreLargo;
        this.giDireccion = giDireccion;
        this.giTelefono = giTelefono;
    }

	
    public TbGiraduria(int giCod, String giNombreCorto, String giNombreLargo) {
        this.giCod = giCod;
        this.giNombreCorto = giNombreCorto;
        this.giNombreLargo = giNombreLargo;
    }
    public TbGiraduria(int giCod, String giNombreCorto, String giNombreLargo, String giDireccion, String giTelefono, Set tbDescuentoses) {
       this.giCod = giCod;
       this.giNombreCorto = giNombreCorto;
       this.giNombreLargo = giNombreLargo;
       this.giDireccion = giDireccion;
       this.giTelefono = giTelefono;
       this.tbDescuentoses = tbDescuentoses;
    }
   
    public int getGiCod() {
        return this.giCod;
    }
    
    public void setGiCod(int giCod) {
        this.giCod = giCod;
    }
    public String getGiNombreCorto() {
        return this.giNombreCorto;
    }
    
    public void setGiNombreCorto(String giNombreCorto) {
        this.giNombreCorto = giNombreCorto;
    }
    public String getGiNombreLargo() {
        return this.giNombreLargo;
    }
    
    public void setGiNombreLargo(String giNombreLargo) {
        this.giNombreLargo = giNombreLargo;
    }
    public String getGiDireccion() {
        return this.giDireccion;
    }
    
    public void setGiDireccion(String giDireccion) {
        this.giDireccion = giDireccion;
    }
    public String getGiTelefono() {
        return this.giTelefono;
    }
    
    public void setGiTelefono(String giTelefono) {
        this.giTelefono = giTelefono;
    }
    public Set getTbDescuentoses() {
        return this.tbDescuentoses;
    }
    
    public void setTbDescuentoses(Set tbDescuentoses) {
        this.tbDescuentoses = tbDescuentoses;
    }




}


