package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0



/**
 * TbGrado generated by hbm2java
 */
public class TbGrado  implements java.io.Serializable {


     private int graCod;
     private String graNombreCorto;
     private String graNombreLargo;

    public TbGrado() {
    }

    public TbGrado(int graCod, String graNombreCorto, String graNombreLargo) {
       this.graCod = graCod;
       this.graNombreCorto = graNombreCorto;
       this.graNombreLargo = graNombreLargo;
    }
   
    public int getGraCod() {
        return this.graCod;
    }
    
    public void setGraCod(int graCod) {
        this.graCod = graCod;
    }
    public String getGraNombreCorto() {
        return this.graNombreCorto;
    }
    
    public void setGraNombreCorto(String graNombreCorto) {
        this.graNombreCorto = graNombreCorto;
    }
    public String getGraNombreLargo() {
        return this.graNombreLargo;
    }
    
    public void setGraNombreLargo(String graNombreLargo) {
        this.graNombreLargo = graNombreLargo;
    }




}


