package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0



/**
 * TbModulos generated by hbm2java
 */
public class TbModulos  implements java.io.Serializable {


     private int modCod;
     private String modNombre;

    public TbModulos() {
    }

	
    public TbModulos(int modCod) {
        this.modCod = modCod;
    }
    public TbModulos(int modCod, String modNombre) {
       this.modCod = modCod;
       this.modNombre = modNombre;
    }
   
    public int getModCod() {
        return this.modCod;
    }
    
    public void setModCod(int modCod) {
        this.modCod = modCod;
    }
    public String getModNombre() {
        return this.modNombre;
    }
    
    public void setModNombre(String modNombre) {
        this.modNombre = modNombre;
    }




}


