package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbPersonalTipo generated by hbm2java
 */
public class TbPersonalTipo  implements java.io.Serializable {


     private int petCod;
     private String petNombre;
     private Set tbPersonals = new HashSet(0);

    public TbPersonalTipo() {
    }

    public TbPersonalTipo(int petCod, String petNombre) {
        this.petCod = petCod;
        this.petNombre = petNombre;
    }

	
    public TbPersonalTipo(int petCod) {
        this.petCod = petCod;
    }
    public TbPersonalTipo(int petCod, String petNombre, Set tbPersonals) {
       this.petCod = petCod;
       this.petNombre = petNombre;
       this.tbPersonals = tbPersonals;
    }
   
    public int getPetCod() {
        return this.petCod;
    }
    
    public void setPetCod(int petCod) {
        this.petCod = petCod;
    }
    public String getPetNombre() {
        return this.petNombre;
    }
    
    public void setPetNombre(String petNombre) {
        this.petNombre = petNombre;
    }
    public Set getTbPersonals() {
        return this.tbPersonals;
    }
    
    public void setTbPersonals(Set tbPersonals) {
        this.tbPersonals = tbPersonals;
    }




}


