package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbPersonal generated by hbm2java
 */
public class TbPersonal  implements java.io.Serializable {


     private int perCod;
     private TbUnidad tbUnidad;
     private TbPersonalTipo tbPersonalTipo;
     private TbCargo tbCargo;
     private int perNum;
     private String perNombre;
     private String perApellido;
     private Integer perCi;
     private String perGrado;
     private String perArma;
     private int ecCod;
     private Integer perAntiguedad;
     private Integer perCategoria;
     private Set tbSueldosXPersonals = new HashSet(0);
     private Set tbDescuentoses = new HashSet(0);
     private Set tbBonificacionesXPersonals = new HashSet(0);

    public TbPersonal() {
    }

	
    public TbPersonal(int perCod, TbPersonalTipo tbPersonalTipo, int perNum, int ecCod) {
        this.perCod = perCod;
        this.tbPersonalTipo = tbPersonalTipo;
        this.perNum = perNum;
        this.ecCod = ecCod;
    }
    public TbPersonal(int perCod, TbUnidad tbUnidad, TbPersonalTipo tbPersonalTipo, TbCargo tbCargo, int perNum, String perNombre, String perApellido, Integer perCi, String perGrado, String perArma, int ecCod, Integer perAntiguedad, Integer perCategoria, Set tbSueldosXPersonals, Set tbDescuentoses, Set tbBonificacionesXPersonals) {
       this.perCod = perCod;
       this.tbUnidad = tbUnidad;
       this.tbPersonalTipo = tbPersonalTipo;
       this.tbCargo = tbCargo;
       this.perNum = perNum;
       this.perNombre = perNombre;
       this.perApellido = perApellido;
       this.perCi = perCi;
       this.perGrado = perGrado;
       this.perArma = perArma;
       this.ecCod = ecCod;
       this.perAntiguedad = perAntiguedad;
       this.perCategoria = perCategoria;
       this.tbSueldosXPersonals = tbSueldosXPersonals;
       this.tbDescuentoses = tbDescuentoses;
       this.tbBonificacionesXPersonals = tbBonificacionesXPersonals;
    }
   
    public int getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(int perCod) {
        this.perCod = perCod;
    }
    public TbUnidad getTbUnidad() {
        return this.tbUnidad;
    }
    
    public void setTbUnidad(TbUnidad tbUnidad) {
        this.tbUnidad = tbUnidad;
    }
    public TbPersonalTipo getTbPersonalTipo() {
        return this.tbPersonalTipo;
    }
    
    public void setTbPersonalTipo(TbPersonalTipo tbPersonalTipo) {
        this.tbPersonalTipo = tbPersonalTipo;
    }
    public TbCargo getTbCargo() {
        return this.tbCargo;
    }
    
    public void setTbCargo(TbCargo tbCargo) {
        this.tbCargo = tbCargo;
    }
    public int getPerNum() {
        return this.perNum;
    }
    
    public void setPerNum(int perNum) {
        this.perNum = perNum;
    }
    public String getPerNombre() {
        return this.perNombre;
    }
    
    public void setPerNombre(String perNombre) {
        this.perNombre = perNombre;
    }
    public String getPerApellido() {
        return this.perApellido;
    }
    
    public void setPerApellido(String perApellido) {
        this.perApellido = perApellido;
    }
    public Integer getPerCi() {
        return this.perCi;
    }
    
    public void setPerCi(Integer perCi) {
        this.perCi = perCi;
    }
    public String getPerGrado() {
        return this.perGrado;
    }
    
    public void setPerGrado(String perGrado) {
        this.perGrado = perGrado;
    }
    public String getPerArma() {
        return this.perArma;
    }
    
    public void setPerArma(String perArma) {
        this.perArma = perArma;
    }
    public int getEcCod() {
        return this.ecCod;
    }
    
    public void setEcCod(int ecCod) {
        this.ecCod = ecCod;
    }
    public Integer getPerAntiguedad() {
        return this.perAntiguedad;
    }
    
    public void setPerAntiguedad(Integer perAntiguedad) {
        this.perAntiguedad = perAntiguedad;
    }
    public Integer getPerCategoria() {
        return this.perCategoria;
    }
    
    public void setPerCategoria(Integer perCategoria) {
        this.perCategoria = perCategoria;
    }
    public Set getTbSueldosXPersonals() {
        return this.tbSueldosXPersonals;
    }
    
    public void setTbSueldosXPersonals(Set tbSueldosXPersonals) {
        this.tbSueldosXPersonals = tbSueldosXPersonals;
    }
    public Set getTbDescuentoses() {
        return this.tbDescuentoses;
    }
    
    public void setTbDescuentoses(Set tbDescuentoses) {
        this.tbDescuentoses = tbDescuentoses;
    }
    public Set getTbBonificacionesXPersonals() {
        return this.tbBonificacionesXPersonals;
    }
    
    public void setTbBonificacionesXPersonals(Set tbBonificacionesXPersonals) {
        this.tbBonificacionesXPersonals = tbBonificacionesXPersonals;
    }




}


