package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0



/**
 * TbRolesXPantallas generated by hbm2java
 */
public class TbRolesXPantallas  implements java.io.Serializable {


     private int ropCod;
     private TbRoles tbRoles;
     private TbPantallas tbPantallas;
     private Boolean panAdd;
     private Boolean panEdit;
     private Boolean panDelete;

    public TbRolesXPantallas() {
    }

	
    public TbRolesXPantallas(int ropCod, TbRoles tbRoles, TbPantallas tbPantallas) {
        this.ropCod = ropCod;
        this.tbRoles = tbRoles;
        this.tbPantallas = tbPantallas;
    }
    public TbRolesXPantallas(int ropCod, TbRoles tbRoles, TbPantallas tbPantallas, Boolean panAdd, Boolean panEdit, Boolean panDelete) {
       this.ropCod = ropCod;
       this.tbRoles = tbRoles;
       this.tbPantallas = tbPantallas;
       this.panAdd = panAdd;
       this.panEdit = panEdit;
       this.panDelete = panDelete;
    }
   
    public int getRopCod() {
        return this.ropCod;
    }
    
    public void setRopCod(int ropCod) {
        this.ropCod = ropCod;
    }
    public TbRoles getTbRoles() {
        return this.tbRoles;
    }
    
    public void setTbRoles(TbRoles tbRoles) {
        this.tbRoles = tbRoles;
    }
    public TbPantallas getTbPantallas() {
        return this.tbPantallas;
    }
    
    public void setTbPantallas(TbPantallas tbPantallas) {
        this.tbPantallas = tbPantallas;
    }
    public Boolean getPanAdd() {
        return this.panAdd;
    }
    
    public void setPanAdd(Boolean panAdd) {
        this.panAdd = panAdd;
    }
    public Boolean getPanEdit() {
        return this.panEdit;
    }
    
    public void setPanEdit(Boolean panEdit) {
        this.panEdit = panEdit;
    }
    public Boolean getPanDelete() {
        return this.panDelete;
    }
    
    public void setPanDelete(Boolean panDelete) {
        this.panDelete = panDelete;
    }




}


