package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbRoles generated by hbm2java
 */
public class TbRoles  implements java.io.Serializable {


     private int rolCod;
     private String rolNombre;
     private Set tbRolesXPantallases = new HashSet(0);

    public TbRoles() {
    }

	
    public TbRoles(int rolCod) {
        this.rolCod = rolCod;
    }
    public TbRoles(int rolCod, String rolNombre, Set tbRolesXPantallases) {
       this.rolCod = rolCod;
       this.rolNombre = rolNombre;
       this.tbRolesXPantallases = tbRolesXPantallases;
    }
   
    public int getRolCod() {
        return this.rolCod;
    }
    
    public void setRolCod(int rolCod) {
        this.rolCod = rolCod;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public Set getTbRolesXPantallases() {
        return this.tbRolesXPantallases;
    }
    
    public void setTbRolesXPantallases(Set tbRolesXPantallases) {
        this.tbRolesXPantallases = tbRolesXPantallases;
    }




}


