package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TbSueldosXPersonal generated by hbm2java
 */
public class TbSueldosXPersonal  implements java.io.Serializable {


     private int supCod;
     private TbPersonal tbPersonal;
     private TbSueldos tbSueldos;
     private int supMonto;
     private Date supFecha;

    public TbSueldosXPersonal() {
    }

    public TbSueldosXPersonal(int supCod, TbPersonal tbPersonal, TbSueldos tbSueldos, int supMonto, Date supFecha) {
       this.supCod = supCod;
       this.tbPersonal = tbPersonal;
       this.tbSueldos = tbSueldos;
       this.supMonto = supMonto;
       this.supFecha = supFecha;
    }
   
    public int getSupCod() {
        return this.supCod;
    }
    
    public void setSupCod(int supCod) {
        this.supCod = supCod;
    }
    public TbPersonal getTbPersonal() {
        return this.tbPersonal;
    }
    
    public void setTbPersonal(TbPersonal tbPersonal) {
        this.tbPersonal = tbPersonal;
    }
    public TbSueldos getTbSueldos() {
        return this.tbSueldos;
    }
    
    public void setTbSueldos(TbSueldos tbSueldos) {
        this.tbSueldos = tbSueldos;
    }
    public int getSupMonto() {
        return this.supMonto;
    }
    
    public void setSupMonto(int supMonto) {
        this.supMonto = supMonto;
    }
    public Date getSupFecha() {
        return this.supFecha;
    }
    
    public void setSupFecha(Date supFecha) {
        this.supFecha = supFecha;
    }




}


