package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbSueldos generated by hbm2java
 */
public class TbSueldos  implements java.io.Serializable {

     private int sueCod;
     private String sueNombre;
     private Set tbSueldosXPersonals = new HashSet(0);

    public TbSueldos() {
    }

	
    public TbSueldos(int sueCod) {
        this.sueCod = sueCod;
    }

    public TbSueldos(int sueCod, String sueNombre) {
        this.sueCod = sueCod;
        this.sueNombre = sueNombre;
    }
    
    public TbSueldos(int sueCod, String sueNombre, Set tbSueldosXPersonals) {
       this.sueCod = sueCod;
       this.sueNombre = sueNombre;
       this.tbSueldosXPersonals = tbSueldosXPersonals;
    }
   
    public int getSueCod() {
        return this.sueCod;
    }
    
    public void setSueCod(int sueCod) {
        this.sueCod = sueCod;
    }
    public String getSueNombre() {
        return this.sueNombre;
    }
    
    public void setSueNombre(String sueNombre) {
        this.sueNombre = sueNombre;
    }
    public Set getTbSueldosXPersonals() {
        return this.tbSueldosXPersonals;
    }
    
    public void setTbSueldosXPersonals(Set tbSueldosXPersonals) {
        this.tbSueldosXPersonals = tbSueldosXPersonals;
    }




}


