package hibernate.pojo;
// Generated 30/01/2014 01:58:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbUnidad generated by hbm2java
 */
public class TbUnidad  implements java.io.Serializable {


     private int uniCod;
     private String uniNombreCorto;
     private String uniNombreLargo;
     private Set tbPersonals = new HashSet(0);

    public TbUnidad() {
    }

	
    public TbUnidad(int uniCod, String uniNombreCorto, String uniNombreLargo) {
        this.uniCod = uniCod;
        this.uniNombreCorto = uniNombreCorto;
        this.uniNombreLargo = uniNombreLargo;
    }
    public TbUnidad(int uniCod, String uniNombreCorto, String uniNombreLargo, Set tbPersonals) {
       this.uniCod = uniCod;
       this.uniNombreCorto = uniNombreCorto;
       this.uniNombreLargo = uniNombreLargo;
       this.tbPersonals = tbPersonals;
    }
   
    public int getUniCod() {
        return this.uniCod;
    }
    
    public void setUniCod(int uniCod) {
        this.uniCod = uniCod;
    }
    public String getUniNombreCorto() {
        return this.uniNombreCorto;
    }
    
    public void setUniNombreCorto(String uniNombreCorto) {
        this.uniNombreCorto = uniNombreCorto;
    }
    public String getUniNombreLargo() {
        return this.uniNombreLargo;
    }
    
    public void setUniNombreLargo(String uniNombreLargo) {
        this.uniNombreLargo = uniNombreLargo;
    }
    public Set getTbPersonals() {
        return this.tbPersonals;
    }
    
    public void setTbPersonals(Set tbPersonals) {
        this.tbPersonals = tbPersonals;
    }




}


